export const THEMES = [
  'Expression',
  'Proverbe',
  'Film',
  'Cuisine',
  'Lieu',
  'Objet',
  'Chanson',
  'Animal',
  'Personnage',
] as const;

export type Theme = (typeof THEMES)[number];

export interface Phrase {
  text: string;
  theme: Theme;
}

export const PHRASES: readonly Phrase[] = [
  { theme: 'Expression', text: 'Avoir le cœur sur la main' },
  { theme: 'Expression', text: 'Poser un lapin' },
  { theme: 'Expression', text: 'Coûter les yeux de la tête' },
  { theme: 'Expression', text: 'Avoir un poil dans la main' },
  { theme: 'Expression', text: 'Tomber dans les pommes' },
  { theme: 'Expression', text: 'Mettre son grain de sel' },
  { theme: 'Expression', text: 'Casser les pieds' },
  { theme: 'Expression', text: "Prendre la poudre d'escampette" },
  { theme: 'Proverbe', text: "Petit à petit, l'oiseau fait son nid" },
  { theme: 'Proverbe', text: 'Qui vivra verra' },
  { theme: 'Proverbe', text: "L'habit ne fait pas le moine" },
  { theme: 'Proverbe', text: "Pierre qui roule n'amasse pas mousse" },
  { theme: 'Proverbe', text: 'La nuit porte conseil' },
  { theme: 'Proverbe', text: 'Tout vient à point à qui sait attendre' },
  { theme: 'Proverbe', text: 'Après la pluie, le beau temps' },
  { theme: 'Film', text: 'Le Seigneur des anneaux' },
  { theme: 'Film', text: 'Le Roi lion' },
  { theme: 'Film', text: "Bienvenue chez les Ch'tis" },
  { theme: 'Film', text: "Le Fabuleux Destin d'Amélie Poulain" },
  { theme: 'Film', text: 'Les Visiteurs' },
  { theme: 'Film', text: 'La Reine des neiges' },
  { theme: 'Film', text: 'Intouchables' },
  { theme: 'Cuisine', text: 'Blanquette de veau' },
  { theme: 'Cuisine', text: 'Bœuf bourguignon' },
  { theme: 'Cuisine', text: 'Tarte aux pommes' },
  { theme: 'Cuisine', text: 'Gratin dauphinois' },
  { theme: 'Cuisine', text: 'Mousse au chocolat' },
  { theme: 'Cuisine', text: 'Crêpes Suzette' },
  { theme: 'Cuisine', text: 'Pot-au-feu' },
  { theme: 'Lieu', text: 'La tour Eiffel' },
  { theme: 'Lieu', text: 'Le mont Saint-Michel' },
  { theme: 'Lieu', text: 'Les Champs-Élysées' },
  { theme: 'Lieu', text: "La Côte d'Azur" },
  { theme: 'Lieu', text: 'Le château de Versailles' },
  { theme: 'Lieu', text: 'La place de la Concorde' },
  { theme: 'Objet', text: 'Une machine à laver' },
  { theme: 'Objet', text: 'Un tire-bouchon' },
  { theme: 'Objet', text: 'Un parapluie' },
  { theme: 'Objet', text: 'Une brosse à dents' },
  { theme: 'Objet', text: 'Un aspirateur' },
  { theme: 'Objet', text: 'Une table de chevet' },
];

/** Final round answers: short names of things, places, songs… Never expressions. */
export const FINAL_PHRASES: readonly Phrase[] = [
  { theme: 'Objet', text: 'Une tondeuse' },
  { theme: 'Objet', text: 'Une brouette' },
  { theme: 'Objet', text: 'Une boussole' },
  { theme: 'Objet', text: 'Un arrosoir' },
  { theme: 'Objet', text: 'Une trottinette' },
  { theme: 'Objet', text: 'Un sablier' },
  { theme: 'Objet', text: 'Une lampe de poche' },
  { theme: 'Objet', text: 'Un grille-pain' },
  { theme: 'Lieu', text: 'Le mont Blanc' },
  { theme: 'Lieu', text: 'La baie de Somme' },
  { theme: 'Lieu', text: 'Les gorges du Verdon' },
  { theme: 'Lieu', text: 'La dune du Pilat' },
  { theme: 'Lieu', text: 'Le pont du Gard' },
  { theme: 'Lieu', text: "Le lac d'Annecy" },
  { theme: 'Chanson', text: 'Les lacs du Connemara' },
  { theme: 'Chanson', text: 'La Bohème' },
  { theme: 'Chanson', text: 'La vie en rose' },
  { theme: 'Chanson', text: 'Alexandrie Alexandra' },
  { theme: 'Chanson', text: 'Le lion est mort ce soir' },
  { theme: 'Film', text: 'Le Grand Bleu' },
  { theme: 'Film', text: 'Les Bronzés' },
  { theme: 'Film', text: 'La Grande Vadrouille' },
  { theme: 'Film', text: 'Le Dîner de cons' },
  { theme: 'Animal', text: 'Un hérisson' },
  { theme: 'Animal', text: 'Un flamant rose' },
  { theme: 'Animal', text: 'Une coccinelle' },
  { theme: 'Animal', text: 'Un ours polaire' },
  { theme: 'Personnage', text: 'Astérix' },
  { theme: 'Personnage', text: 'Le Petit Prince' },
  { theme: 'Personnage', text: 'Cendrillon' },
];

/** Toss-up puzzles: a bit longer, so that the letters take a while to fill the board. */
export const TOSS_UP_PHRASES: readonly Phrase[] = [
  { theme: 'Expression', text: 'Être dans la lune' },
  { theme: 'Expression', text: 'Avoir la tête dans les nuages' },
  { theme: 'Expression', text: 'Mettre la charrue avant les bœufs' },
  { theme: 'Expression', text: 'Chercher une aiguille dans une botte de foin' },
  { theme: 'Expression', text: 'Donner sa langue au chat' },
  { theme: 'Expression', text: 'Faire la grasse matinée' },
  { theme: 'Expression', text: "Avoir une mémoire d'éléphant" },
  { theme: 'Proverbe', text: 'Qui va à la chasse perd sa place' },
  { theme: 'Proverbe', text: 'Les bons comptes font les bons amis' },
  { theme: 'Proverbe', text: 'Mieux vaut tard que jamais' },
  { theme: 'Film', text: 'Les Demoiselles de Rochefort' },
  { theme: 'Film', text: 'Le père Noël est une ordure' },
  { theme: 'Film', text: 'La Cité de la peur' },
  { theme: 'Film', text: 'Retour vers le futur' },
  { theme: 'Film', text: "Harry Potter à l'école des sorciers" },
  { theme: 'Cuisine', text: 'Une tartiflette savoyarde' },
  { theme: 'Cuisine', text: 'Une galette des rois' },
  { theme: 'Cuisine', text: 'Une île flottante' },
  { theme: 'Cuisine', text: 'Une crème brûlée' },
  { theme: 'Lieu', text: 'Les châteaux de la Loire' },
  { theme: 'Lieu', text: 'Le cirque de Gavarnie' },
  { theme: 'Lieu', text: "L'Arc de triomphe" },
  { theme: 'Lieu', text: 'La promenade des Anglais' },
  { theme: 'Objet', text: 'Un fer à repasser' },
  { theme: 'Objet', text: 'Une machine à café' },
  { theme: 'Objet', text: 'Un sèche-cheveux' },
  { theme: 'Chanson', text: 'Allumer le feu' },
  { theme: 'Chanson', text: 'Douce France' },
  { theme: 'Chanson', text: 'Je te promets' },
  { theme: 'Chanson', text: 'La danse des canards' },
  { theme: 'Animal', text: 'Un chien de berger' },
  { theme: 'Animal', text: 'Une baleine à bosse' },
  { theme: 'Animal', text: 'Un poisson rouge' },
  { theme: 'Personnage', text: 'Le capitaine Haddock' },
  { theme: 'Personnage', text: 'La fée Clochette' },
  { theme: 'Personnage', text: 'Le Petit Chaperon rouge' },
  { theme: 'Personnage', text: 'Blanche-Neige et les sept nains' },
];
