import { group, type Phrase } from './theme';

/**
 * Final round answers: short names of things, places, songs… Never expressions.
 * R S T L N E are given for free: they make up only 5 to 25 % of the letters.
 */
export const FINAL_PHRASES: readonly Phrase[] = [
  ...group('Animal', [
    'Koala',
    'Panda',
    'Chimpanzé',
    'Macaque',
    'Hippopotame',
    'Dauphin',
    'Phoque',
    'Mouche',
    'Cachalot',
    'Chacal',
    'Caribou',
    'Wapiti',
    'Jaguar',
    'Impala',
    'Gibbon',
    'Babouin',
    'Capucin',
    'Chameau',
    'Alpaga',
    'Chamois',
    'Cabri',
    'Cochon',
    'Paon',
    'Macareux',
    'Pingouin',
    'Kookaburra',
    'Faucon',
    'Ibis',
    'Kangourou',
    'Wombat',
    'Zébu',
    'Gnou',
    'Cobaye',
    'Gecko',
    'Cobra',
    'Crapaud',
    'Homard',
    'Coque',
    'Barracuda',
    'Cabillaud',
    'Puce',
    'Cafard',
    'Fourmi',
    'Husky',
    'Dogue',
    'Bichon',
    'Campagnol',
    'Choucas',
    'Geai',
    'Huppe',
    'Un hibou',
    'Un kiwi',
    'Un coucou',
    'Un okapi',
    'Un yak',
    'Un puma',
    'Un maki',
    'Un bouc',
    'Un coq',
    'Un boa',
    'Un mamba',
    'Un pou',
    'Un chihuahua',
    'Un chow-chow',
    'Un hippocampe',
    'Un capybara',
    'Un dodo',
    'Un macaque japonais',
    'Un dahu',
    'Un hippogriffe',
    'Anaconda',
    'Un caïman',
    'Un couguar',
    'Un kinkajou',
    'Loup',
    'Un mammouth',
    'Marabout',
    'Un quokka',
    'Un sapajou',
    'Biche',
    'Vache',
    'Un bonobo',
    'Un pika',
    'Un addax',
    'Un koudou',
    'Un dik-dik',
    'Un kakapo',
    'Un barzoï',
    'Un mahi-mahi',
    'Un pic',
  ]),
  ...group('Objet', [
    'Mouchoir',
    'Cadeau',
    'Aquarium',
    'Jukebox',
    'Kimono',
    'Poncho',
    'Bouquin',
    'Couche',
    'Bavoir',
    'Chapeau',
    'Képi',
    'Bague',
    'Bougie',
    'Bocal',
    'Hachoir',
    'Shampoing',
    'Parfum',
    'Doudoune',
    'Boîte à bijoux',
    'Badge',
    'Sac à main',
    'Cabas',
    'Abat-jour',
    'Bougeoir',
    'Compas',
    'Bloc',
    'Pochoir',
    'Gomme',
    'Gouache',
    'Piccolo',
    'Domino',
    'Hula-hoop',
    'Diabolo',
    'Kapla',
    'Playmobil',
    'Babouche',
    'Paquebot',
    'Kimono de judo',
    'Cape',
    'Jabot',
    'Polo',
    'Jogging',
    'Monokini',
    'Bikini',
    'Un yoyo',
    'Un kayak',
    'Un doudou',
    'Un joujou',
    'Un pouf',
    'Un bambou',
    'Un cachou',
    'Un wok',
    'Un kazoo',
    'Un pogo',
    'Un mikado',
    'Un bigoudi',
    'Un chouchou',
    'Une chapka',
    'Un body',
    'Un pyjama',
    'Un jacuzzi',
    'Un bijou',
    'Un boubou',
    'Un hamac',
    'Un bouchon',
    'Un bouzouki',
    'Un quiz',
    'Un hobby',
    'Un capuchon',
    'Un abaque',
    'Un poupon',
    'Un cache-cou',
    'Un pique-bœuf',
    'Un accoudoir',
    'Un album photo',
    'Baldaquin',
    'Baluchon',
    'Bidon',
    'Un bivouac',
    'Un boudoir',
    'Un caddie',
    'Un caoutchouc',
    'Capot',
    'Un casque audio',
    'Chapiteau',
    'Cocon',
    'Un couffin',
    'Fagot',
    'Un fichu',
    'Flambeau',
    'Un guidon',
    'Un judo',
    'Un magnum',
    'Micro',
    'Objectif',
    'Un podium',
    'Un pommeau',
    'Tipi',
    'Toboggan',
    'Tuyau',
    'Wagon',
    'Capuche',
    'Jauge',
    'Pagaie',
    'Pipe',
    'Radio',
    'Un chapka',
    'Magazine',
    'Patchwork',
    'Coupe à champagne',
    'Hache',
    'Pioche',
    'Cage à oiseaux',
  ]),
  ...group('Cuisine', [
    'Chocolat chaud',
    'Champignon',
    'Cookie',
    'Avocat',
    'Cappuccino',
    'Hot-dog',
    'Couscous',
    'Kebab',
    'Hachis',
    'Chips',
    'Macaroni',
    'Gnocchi',
    'Cookie au chocolat',
    'Muffin',
    'Cupcake',
    'Baklava',
    'Loukoum',
    'Chocolat',
    'Guimauve',
    'Bobun',
    'Dim sum',
    'Houmous',
    'Pita',
    'Guacamole',
    'Chili',
    'Quiche',
    'Jambon',
    'Chorizo',
    'Boudin',
    'Bœuf',
    'Veau',
    'Gaspacho',
    'Aïoli',
    'Pain au chocolat',
    'Baba au rhum',
    'Pavlova',
    'Café',
    'Jus de coco',
    'Whisky',
    'Champagne',
    'Grog',
    'Une pizza',
    'Un mochi',
    'Un gyoza',
    'Un gouda',
    'Une focaccia',
    'Un moka',
    'Un cacao',
    'Un kombucha',
    'Un coca',
    'Une vodka',
    'Un chou',
    'Un gombo',
    'Un haddock',
    'Un mojito',
    'Un chaï',
    'Un ouzo',
    'Un cacao chaud',
    'Un chou farci',
    'Un kouglof',
    'Un mochi glacé',
    'Un cappuccino glacé',
    'Un bobun au bœuf',
    'Un bœuf au paprika',
    'Un flan au coco',
    'Un baba',
    'Une babka',
    'Un œuf mimosa',
    'Un pain au maïs',
    'Un macchiato',
    'Un cookie aux noix',
    'Un cupcake au chocolat',
    'Un milk-shake au cacao',
    'Un croque au jambon',
    'Un hot-dog au ketchup',
    'Cake',
    'Un carpaccio',
    'Un caviar',
    'Un chapon',
    'Un pudding',
    'Un tapioca',
    'Moussaka',
    'Un muffin au chocolat',
    'Un bol de cacao',
    'Un cappuccino au cacao',
    'Un pho au bœuf',
    'Un bao',
    'Un mochi à la mangue',
    'Un taco au bœuf',
    'Une pizza au chorizo',
    'Une pizza au jambon',
    'Pad thaï',
    'Dahl',
    'Udon',
    'Baba ganoush',
    'Chapati',
    'Pakora',
    'Un mochi au chocolat',
    'Un pudding au chocolat',
    'Un chou au chocolat',
    'Un muffin au cacao',
  ]),
  ...group('Fruit et légume', [
    'Papaye',
    'Goyave',
    'Pomme',
    'Coing',
    'Figue',
    'Kumquat',
    'Jacquier',
    'Pois chiche',
    'Soja',
    'Maïs',
    'Manioc',
    'Okra',
    'Paprika',
    'Cumin',
    'Curcuma',
    'Noix de cajou',
    'Noix',
    'Wasabi',
    'Un kaki',
    'Une noix de macadamia',
  ]),
  ...group('Lieu', [
    'Bora-Bora',
    'Monaco',
    'Acapulco',
    'Hong Kong',
    'Moscou',
    'Tokyo',
    'Panama',
    'Bali',
    'Malaga',
    'Majorque',
    'Corfou',
    'Capri',
    'Mexico',
    'Bogota',
    'Lima',
    'Quito',
    'Cusco',
    'Copacabana',
    'Agra',
    'Katmandou',
    'Bangkok',
    'Hanoï',
    'Kyoto',
    'Osaka',
    'Okinawa',
    'Djakarta',
    'Papouasie',
    'Auckland',
    'Dakar',
    'Abidjan',
    'Accra',
    'Douala',
    'Djibouti',
    'Kampala',
    'Zanzibar',
    'Mombasa',
    'Kigali',
    'Maputo',
    'Windhoek',
    'Agadir',
    'Kairouan',
    'Gizeh',
    'Pompéi',
    'Padoue',
    'Pavie',
    'Mâcon',
    'Dijon',
    'Cognac',
    'Bougival',
    'Bourg',
    'Albi',
    'Bobigny',
    'Cachan',
    'Chamonix',
    'Maubeuge',
    'Cambrai',
    'Chambéry',
    'Arcachon',
    'Bonifacio',
    'Porto-Vecchio',
    'Calvi',
    'Un zoo',
    'Le Machu Picchu',
    'Un cachot',
    'Un quai',
    'Un hammam',
    'Un bocage',
    'Un bayou',
    'Hiroshima',
    'Nagasaki',
    'Kobe',
    'Cebu',
    'Addis-Abeba',
    'Amman',
    'Ischia',
    'Palma',
    'Bilbao',
    'Oviedo',
    'Coimbra',
    'Faro',
    "Cap d'Agde",
    'Chambord',
    'Malakoff',
    'Choisy',
    'Bondy',
    'Champigny',
    'Avoriaz',
    'Auray',
    'Bungalow',
    'Un caveau',
    'Un dojo',
    'Fjord',
    'Souk',
    'Abbaye',
    'Bodega',
    'Pagode',
    'Okavango',
    'Kalahari',
    'Mojave',
    'Atacama',
    'Fukushima',
    'Hakodate',
    'Kagoshima',
    'Nagoya',
    'Shanghai',
    'Mandalay',
    'Damas',
    'Djeddah',
    'Mopti',
    'Tombouctou',
    'Mahajanga',
    'Yamoussoukro',
    'Guadalajara',
    'Arequipa',
    'Maracaña',
    'Ushuaïa',
    'Cordoba',
    'Guayaquil',
    'Cali',
    'Maracaibo',
    'Curaçao',
    'Aruba',
    'Oklahoma',
    'Colorado',
    'Dakota',
    'Wyoming',
    'Alabama',
    'Hollywood',
    'Michigan',
    'Yukon',
    'Manitoba',
    'Hyderabad',
    'Bhopal',
    'Jaipur',
    'Udaipur',
    'Pokhara',
    'Kiev',
    'Kamtchatka',
    'Baïkal',
    'Kazan',
    'Bodrum',
    'Cappadoce',
    'Izmir',
    'Amalfi',
    'Côme',
    'Cadaqués',
    'La Paz',
    'Chiang Mai',
    'Bagan',
  ]),
  ...group('Personnage', [
    'Picsou',
    'Babar',
    'Mowgli',
    'Pinocchio',
    'Mickey',
    'Dingo',
    'Daisy',
    'Luffy',
    'Kirikou',
    'Moana',
    'Vaiana',
    'Jafar',
    'Baloo',
    'Dopey',
    'Joyeux',
    'Prof',
    'Atchoum',
    'Rafiki',
    'Mufasa',
    'Kiara',
    'Jiminy',
    'Porky Pig',
    'Scooby-Doo',
    'Sammy',
    'Odie',
    'Woodstock',
    'Idéfix',
    'Panoramix',
    'Abraracourcix',
    'Dupond',
    'Milou',
    'Mafalda',
    'Nadia',
    'Spip',
    'Barbapapa',
    'Mushu',
    'Un cow-boy',
    'Un zombie',
    'Un viking',
    'Un chaman',
    'Un bouffon',
    'Phil',
    'Mimi Cracra',
    "Pomme d'Api",
    'Zurg',
    'Mike Wazowski',
    'Bob Razowski',
    'Dory',
    'Doc Hudson',
    'Margo',
    'Dave',
    'Fiona',
    'Lord Farquaad',
    'Bibendum',
    'Goldorak',
    'Candy',
    'Heidi',
    'Buck Danny',
    'Iznogoud',
    'Hathi',
    'Placid et Muzo',
    'Yakari',
    'Kid Paddle',
    'Peppa',
    'Maman Pig',
    'Mbappé',
    'Giroud',
    'Maradona',
    'Papin',
    'Noah',
    'Aznavour',
    'Édith Piaf',
    'Dalida',
    'Bécaud',
    'Kad Merad',
    'Dany Boon',
    'Mimie Mathy',
    'Dark Vador',
    'Chewbacca',
    'Obi-Wan Kenobi',
    'Padmé',
    'Hagrid',
    'Bilbo',
    'Maximus',
    'Olaf',
    'Carapuce',
    'Dracaufeu',
    'Psykokwak',
    'Magicarpe',
    'Rondoudou',
    'Onix',
    'Arbok',
    'Cupidon',
    'Bacchus',
    'Odin',
    'Loki',
    'Shiva',
    'Donald Duck',
    'Chihiro',
  ]),
  ...group('Pays', [
    'Japon',
    'Malawi',
    'Mali',
    'Togo',
    'Gabon',
    'Congo',
    'Ouganda',
    'Uruguay',
    'Paraguay',
    'Haïti',
    'Jamaïque',
    'Bahamas',
    'Samoa',
    'Oman',
    'Irak',
    'Cambodge',
    'Moldavie',
    'Kosovo',
    'Maroc',
    'Zambie',
    'Zimbabwe',
    'Mozambique',
  ]),
  ...group('Instrument', [
    'Banjo',
    'Bongo',
    'Biniou',
    'Bombarde',
    'Harmonica',
    'Hautbois',
    'Tuba',
    'Gong',
    'Cajón',
    'Didgeridoo',
    'Koto',
    'Balalaïka',
    'Piano',
    'Pipeau',
    'Charango',
  ]),
  ...group('Vêtement', [
    'Cache-col',
    'Jupon',
    'Caraco',
    'Parka',
    'Caban',
    'Frac',
    'Un hijab',
    'Un K-way',
    'Un judogi',
    'Un bob',
    'Jupe',
  ]),
  ...group('Super-héros', [
    'Hulk',
    'Aquaman',
    'Cyborg',
    'Shazam',
    'Gamora',
    'Drax',
    'Malicia',
    'Diablo',
    'Hope',
    'Okoye',
  ]),
  ...group('Jeu vidéo', [
    'Pac-Man',
    'Kirby',
    'Mario',
    'Luigi',
    'Peach',
    'Yoshi',
    'Wario',
    'Waluigi',
    'Toad',
    'Halo',
    'Pong',
    'Game Boy',
    'Joystick',
    'Pikmin',
    'Diddy Kong',
    'Pokémon Go',
    'Dofus',
    'Rock Band',
    'Wii Fit',
    'Joy-Con',
    'Game Cube',
  ]),
  ...group('Corps humain', [
    'Joue',
    'Coude',
    'Poing',
    'Pouce',
    'Paume',
    'Tibia',
    'Bouche',
    'Mâchoire',
    'Bajoue',
    'Diaphragme',
    'Foie',
    'Duodénum',
    'Un cou',
    'Un coccyx',
    'Un poumon',
  ]),
  ...group('Monument', [
    'Taj Mahal',
    'Pyramide',
    'Alhambra',
    'Atomium',
    'Borobudur',
    'Uxmal',
    'Lido',
    'Mont Fuji',
    'Kilimandjaro',
    'Himalaya',
  ]),
  ...group('Boisson', [
    'Punch',
    'Calvados',
    'Caïpirinha',
    'Daïquiri',
    'Bloody Mary',
    'Matcha',
    'Raki',
    'Arak',
    'Malibu',
    'Pina colada',
  ]),
  ...group('Véhicule', [
    'Moto',
    'Taxi',
    'Camion',
    'Coupé',
    'Rickshaw',
    'Yacht',
    'Chaloupe',
    'Cargo',
    'Avion',
    'Jumbo-jet',
    'Ovni',
    'Un buggy',
    'Un quad',
    'Un combi',
    'Un zodiac',
    'Hydravion',
  ]),
  ...group('Jeu de société', [
    "Yam's",
    'Monopoly',
    'Bingo',
    'Mahjong',
    'Backgammon',
    'Pickomino',
    'Dixit',
    'Azul',
    'Taboo',
    'Kakuro',
    'Sudoku',
    'Un djambi',
    'Le jeu du mikado',
  ]),
  ...group('Fête', [
    'Hanoucca',
    'Kippour',
    'Diwali',
    'Holi',
    'Méchoui',
    'Communion',
    'Hanoukka',
    'Pourim',
  ]),
  ...group('Nature', [
    'Buis',
    'Hibiscus',
    'Magnolia',
    'Dahlia',
    'Mimosa',
    'Taïga',
    'Igloo',
    'Un baobab',
    'Un if',
    'La pampa',
    'Un houx',
  ]),
  ...group('Métier', [
    'Coiffeur',
    'Chauffeur',
    'Jockey',
    'Majordome',
    'Juge',
    'Magicien',
    'Mime',
    'Un coach',
  ]),
  ...group('Film', [
    'Kung Fu Panda',
    'Madagascar',
    'Rocky',
    'Rambo',
    'Jumanji',
    'Babe',
    'Bad Boys',
    'Pacific Rim',
    'Oblivion',
    'Hobbit',
    'Bohemian Rhapsody',
    'Cocoon',
    'King Kong',
    'Godzilla',
    'Robocop',
    'Camping',
    'Ponyo',
    'Akira',
  ]),
  ...group('Chanson', [
    'Hakuna Matata',
    'Lambada',
    'Papaoutai',
    'Bamboléo',
    'Bambino',
    'Pookie',
    'Au pays du chocolat',
    "Comme d'habitude",
    'Tchiki boum',
    'Zou bisou bisou',
    'Africa',
  ]),
  ...group('Personnage historique', [
    'Gandhi',
    'Abraham',
    'Dali',
    'Gauguin',
    'Chopin',
    'Vivaldi',
    'Haydn',
    'Vasco de Gama',
    'Kubilaï Khan',
    'Confucius',
    'Sapho',
    'Marco Polo',
    'Mao Zedong',
    'Victor Hugo',
    'Mata Hari',
    'Hugo Capet',
    'Bayard',
    'Champlain',
    'Kublai Khan',
    'Hô Chi Minh',
    'Khrouchtchev',
    'Pouchkine',
    'Tchaïkovski',
    'Chostakovitch',
    'Prokofiev',
    'Modigliani',
    'Caravage',
    'Palladio',
    'Machiavel',
    'Borgia',
    'Casanova',
    'Paganini',
    'Puccini',
    'Fibonacci',
    'Maïmonide',
  ]),
  ...group('Sport', [
    "L'aïkido",
    'Kung-fu',
    'Hockey',
    'Golf',
    'Rugby',
    'Boxe',
    'Un judoka',
    'Un coup de pied',
    'Un coup de poing',
    'Un champion',
    'Un hippodrome',
  ]),
];
