import { group, type Phrase } from './theme';

/** Regular round puzzles. Musique: two songs by the same artist, joined by "&". */
export const PHRASES: readonly Phrase[] = [
  ...group('Expression', [
    'Avoir la tête dans les nuages',
    'Avoir les yeux plus gros que le ventre',
    'Mettre les pieds dans le plat',
    'Casser sa pipe',
    'Avoir un chat dans la gorge',
    'Être dans de beaux draps',
    'Prendre la mouche',
    'Donner sa langue au chat',
    'Avoir la main verte',
    'Avoir le bras long',
    'Couper la poire en deux',
    'Faire la grasse matinée',
    'Avoir du pain sur la planche',
    'Tirer les vers du nez',
    'Mettre la charrue avant les bœufs',
    'Se faire rouler dans la farine',
    'Être haut comme trois pommes',
    'Raconter des salades',
    'Avoir la pêche',
    'Avoir la frite',
    'Ne pas être dans son assiette',
    'Mettre son grain de sel',
    'Tourner autour du pot',
    'Être une poule mouillée',
    'Avoir une mémoire de poisson rouge',
    'Avoir des fourmis dans les jambes',
    'Être têtu comme une mule',
    'Avoir le melon',
    'Faire chou blanc',
    "Mettre de l'eau dans son vin",
    "Être comme un poisson dans l'eau",
    'Tomber des cordes',
    'Il pleut des cordes',
    'Avoir le moral dans les chaussettes',
    "Avoir un cœur d'artichaut",
    'Appeler un chat un chat',
    'Avoir la langue bien pendue',
    'Se creuser la tête',
    'Avoir la tête sur les épaules',
    'Prendre ses jambes à son cou',
    'Avoir les chevilles qui enflent',
    "Faire d'une pierre deux coups",
    "Être sur la même longueur d'onde",
    'Mettre la main à la pâte',
    'Avoir le vent en poupe',
    'Être dans la lune',
    'Avoir une faim de loup',
    "Avoir un appétit d'oiseau",
    'Dormir comme un loir',
    'Être muet comme une carpe',
    'Être rusé comme un renard',
    'Être fier comme un paon',
    'Être doux comme un agneau',
    'Être malin comme un singe',
    'Bavard comme une pie',
    'Rouge comme une tomate',
    'Sourd comme un pot',
    'Fort comme un turc',
    'Myope comme une taupe',
    'Haut comme trois pommes',
    'Avoir un coup de barre',
    'Avoir le coup de foudre',
    "Sauter du coq à l'âne",
    'Revenir à ses moutons',
    "Avoir d'autres chats à fouetter",
    'Se mettre sur son trente et un',
    'Être sur son trente et un',
    'Remuer ciel et terre',
    'Avoir le dernier mot',
    'Couper la parole',
    'Voir la vie en rose',
    'Broyer du noir',
    'Être vert de rage',
    'Passer une nuit blanche',
    'Montrer patte blanche',
    'Manger sur le pouce',
    'Mettre les bouchées doubles',
    'Avoir les dents longues',
    'Se serrer la ceinture',
    "Jeter l'argent par les fenêtres",
    'Coûter un bras',
    "Payer rubis sur l'ongle",
    'Faire la sourde oreille',
    "Avoir l'oreille fine",
    'Être tout ouïe',
    'Garder la tête froide',
    'Perdre la tête',
    'Perdre le nord',
    'Ne pas avoir froid aux yeux',
    'Avoir le cœur sur la main',
    'Prendre le taureau par les cornes',
    'Ménager la chèvre et le chou',
    'Quand les poules auront des dents',
    'Il y a anguille sous roche',
    'Être le dindon de la farce',
    'Être une tête de mule',
    'Avoir la chair de poule',
    'Faire un froid de canard',
    'Un temps de chien',
    'Une fièvre de cheval',
    'Avoir le cafard',
    'Avoir une araignée au plafond',
    'Courir sur le haricot',
    'Raconter des histoires',
    'Mettre les points sur les i',
    'Être au pied du mur',
    "Tomber à l'eau",
    'Avoir le nez creux',
    "Mener quelqu'un en bateau",
    'Être aux anges',
    'Être au septième ciel',
    'Tirer son épingle du jeu',
    "Mettre la puce à l'oreille",
    'Ne pas y aller par quatre chemins',
    'Faire la pluie et le beau temps',
    'Avoir plusieurs cordes à son arc',
    "Se noyer dans un verre d'eau",
    'Avoir la grosse tête',
    'Être bête comme ses pieds',
    'Casser les pieds',
    'Avoir les pieds sur terre',
    'Partir en fumée',
    'Avoir le feu sacré',
    'Jouer avec le feu',
    'Péter les plombs',
    'Avoir la main lourde',
    'Donner un coup de main',
    'Faire la tête',
    'Faire contre mauvaise fortune bon cœur',
    'Mettre la main au feu',
    'Tenir la chandelle',
    'En faire tout un fromage',
    'Avoir les yeux en face des trous',
    'Ça ne casse pas trois pattes à un canard',
    'Ne pas avoir sa langue dans sa poche',
    "Rouler sur l'or",
    'Être fauché comme les blés',
    'Avoir un poil dans la main',
    'Il ne faut pas pousser mémé dans les orties',
    'Les doigts dans le nez',
    'Prendre un coup de vieux',
    'Boire comme un trou',
    'Avoir la gueule de bois',
    'Être dans le pétrin',
    'Mettre le feu aux poudres',
    'Avoir un trou de mémoire',
    'Être tiré à quatre épingles',
    "Battre le fer tant qu'il est chaud",
    "Ce n'est pas la mer à boire",
    'Avoir de la bouteille',
    'Mettre sa main à couper',
    'Faire un tabac',
    "Se mettre le doigt dans l'œil",
    "Avoir le compas dans l'œil",
    'Coûter les yeux de la tête',
    'Faire des yeux doux',
    'À vue de nez',
    "Avoir la puce à l'oreille",
    'Enfoncer des portes ouvertes',
    'Ne pas faire long feu',
    'Sortir de ses gonds',
    'Poser un lapin',
    'Tomber dans les pommes',
    "Prendre la poudre d'escampette",
  ]),
  ...group('Proverbe', [
    'Qui vivra verra',
    "L'habit ne fait pas le moine",
    "Petit à petit l'oiseau fait son nid",
    'Tel père tel fils',
    "L'appétit vient en mangeant",
    'Qui va à la chasse perd sa place',
    'Loin des yeux loin du cœur',
    'Mieux vaut tard que jamais',
    "Pierre qui roule n'amasse pas mousse",
    'Après la pluie le beau temps',
    "Chat échaudé craint l'eau froide",
    'Qui sème le vent récolte la tempête',
    "Il n'y a pas de fumée sans feu",
    'Les bons comptes font les bons amis',
    "Qui ne risque rien n'a rien",
    "Un tiens vaut mieux que deux tu l'auras",
    "L'union fait la force",
    'Tout vient à point à qui sait attendre',
    'La nuit porte conseil',
    'Rira bien qui rira le dernier',
    "Qui se ressemble s'assemble",
    "Le temps c'est de l'argent",
    "Paris ne s'est pas fait en un jour",
    "À cœur vaillant rien d'impossible",
    "Quand le chat n'est pas là les souris dansent",
    "La parole est d'argent le silence est d'or",
    "On ne fait pas d'omelette sans casser des œufs",
    'Les murs ont des oreilles',
    'Une hirondelle ne fait pas le printemps',
    'Il ne faut jamais dire jamais',
    'Tout est bien qui finit bien',
    'Qui veut voyager loin ménage sa monture',
    'Les chiens ne font pas des chats',
    "L'erreur est humaine",
    'Comme on fait son lit on se couche',
    "Il faut battre le fer tant qu'il est chaud",
    'Plus on est de fous plus on rit',
    "Vouloir c'est pouvoir",
    'Qui dort dîne',
    'À chaque jour suffit sa peine',
    'Pas de nouvelles bonnes nouvelles',
    'Il y a loin de la coupe aux lèvres',
    'Mieux vaut prévenir que guérir',
    'La fin justifie les moyens',
    'Chose promise chose due',
    'Charité bien ordonnée commence par soi-même',
    'Le chat parti les souris dansent',
    'Il faut tourner sept fois sa langue dans sa bouche',
    'Noël au balcon Pâques au tison',
    "En avril ne te découvre pas d'un fil",
    'Qui aime bien châtie bien',
    'Bien mal acquis ne profite jamais',
    "L'argent ne fait pas le bonheur",
    'Il ne faut pas réveiller le chat qui dort',
    'Les petits ruisseaux font les grandes rivières',
    'Mains froides cœur chaud',
    'Jamais deux sans trois',
    "L'occasion fait le larron",
    "Ventre affamé n'a point d'oreilles",
    'Tous les chemins mènent à Rome',
    'Il faut que jeunesse se passe',
    'Abondance de biens ne nuit pas',
    "On n'apprend pas aux vieux singes à faire la grimace",
    'Qui trop embrasse mal étreint',
  ]),
  ...group('Film', [
    "Le Fabuleux Destin d'Amélie Poulain",
    "Bienvenue chez les Ch'tis",
    'Le Dîner de cons',
    'La Grande Vadrouille',
    'Les Bronzés font du ski',
    'Le père Noël est une ordure',
    'Astérix et Obélix Mission Cléopâtre',
    'Les Tontons flingueurs',
    'La Cité de la peur',
    'Le Grand Bleu',
    'La Vie est belle',
    "Qu'est-ce qu'on a fait au Bon Dieu",
    'Le Seigneur des anneaux',
    "Harry Potter à l'école des sorciers",
    'La Guerre des étoiles',
    'Retour vers le futur',
    'Les Dents de la mer',
    "Le Magicien d'Oz",
    'Pirates des Caraïbes',
    'Le Silence des agneaux',
    'La Ligne verte',
    'Le Cinquième Élément',
    'Le Pacte des loups',
    'Rien à déclarer',
    'Le Gendarme de Saint-Tropez',
    'Les Aventures de Rabbi Jacob',
    "L'Aile ou la Cuisse",
    'Le Grand Restaurant',
    'Brice de Nice',
    'Bienvenue à Gattaca',
    'Les Petits Mouchoirs',
    'Le Sens de la fête',
    'Le Bal des actrices',
    'La Famille Bélier',
    'Les Trois Frères',
    'Les Couloirs du temps',
    'Le Roi Arthur',
    'La Mélodie du bonheur',
    'Le Bon la Brute et le Truand',
    "Il était une fois dans l'Ouest",
    'Men in Black',
    "Maman j'ai raté l'avion",
    'Le Journal de Bridget Jones',
    'La La Land',
    'Le Loup de Wall Street',
    'Le Monde de Nemo',
    'Mon voisin Totoro',
    'Le Voyage de Chihiro',
    "Les Aventuriers de l'arche perdue",
    'La Soupe aux choux',
    'Le Comte de Monte-Cristo',
    'Les Trois Mousquetaires',
    'Le Petit Nicolas',
    'Les Aventures de Tintin',
    'Le Petit Prince',
    'Cyrano de Bergerac',
    'Jean de Florette',
    'Manon des sources',
    'La Gloire de mon père',
    'Le Château de ma mère',
    'Le Goût des autres',
    'Le Grand Blond avec une chaussure noire',
  ]),
  ...group('Dessin animé', [
    'Le Roi lion',
    'La Belle et la Bête',
    'La Petite Sirène',
    'Blanche-Neige et les Sept Nains',
    'La Belle au bois dormant',
    'Le Livre de la jungle',
    'Alice au pays des merveilles',
    'La Reine des neiges',
    'Monstres et Compagnie',
    'Le Monde de Dory',
    "L'Âge de glace",
    'Moi moche et méchant',
    'Kung Fu Panda',
    'Les Mondes de Ralph',
    'La Princesse et la Grenouille',
    'Le Bossu de Notre-Dame',
    'Lilo et Stitch',
    'Astérix le Gaulois',
    "Les Douze Travaux d'Astérix",
    'Tintin et le Lac aux requins',
    'Kirikou et la Sorcière',
    'Les Triplettes de Belleville',
    'Ernest et Célestine',
    'Il était une fois la vie',
    "Les Mystérieuses Cités d'or",
    'Tom et Jerry',
    'Petit Ours Brun',
    'Bob le bricoleur',
    'Les Fous du volant',
    'Les Chevaliers du Zodiaque',
    'Mon petit poney',
    "Les aventures de Winnie l'ourson",
    'Charlie et la chocolaterie',
    'Les Aventures de Bernard et Bianca',
    'Rox et Rouky',
    'Robin des Bois de Disney',
    'Taram et le chaudron magique',
    'Le Château dans le ciel',
  ]),
  ...group('Série TV', [
    'Plus belle la vie',
    'Joséphine ange gardien',
    "Les Feux de l'amour",
    'Game of Thrones',
    'La Casa de papel',
    'Le Bureau des légendes',
    'Dix pour cent',
    'Fais pas ci fais pas ça',
    'Scènes de ménages',
    'Un gars une fille',
    'Hélène et les Garçons',
    'Sous le soleil',
    'Louis la Brocante',
    'Demain nous appartient',
    'Ici tout commence',
    'Un si grand soleil',
    'Le Prince de Bel-Air',
    'Buffy contre les vampires',
    'La Petite Maison dans la prairie',
    "Mystères de l'Ouest",
    'Questions pour un champion',
    'Des chiffres et des lettres',
    'Le Juste Prix',
    'Qui veut gagner des millions',
    "N'oubliez pas les paroles",
    'Les Douze Coups de midi',
    'La Roue de la fortune',
    'Le Meilleur Pâtissier',
    "L'Amour est dans le pré",
    "Les Guignols de l'info",
  ]),
  ...group('Musique', [
    'Ne me quitte pas & Amsterdam',
    'Le Plat Pays & Les Bonbons',
    "Quand on n'a que l'amour & La Valse à mille temps",
    'La Vie en rose & Non je ne regrette rien',
    "Milord & L'Hymne à l'amour",
    'Padam padam & La Foule',
    'Hier encore & For me formidable',
    'Les Comédiens & Comme ils disent',
    "Noir c'est noir & Gabrielle",
    'Requiem pour un fou & Marie',
    "L'Envie & Je te promets",
    'Envole-moi & Je te donne',
    'Quand la musique est bonne & Encore un matin',
    "Il suffira d'un signe & Au bout de mes rêves",
    'Là-bas & Puisque tu pars',
    'Les Lacs du Connemara & En chantant',
    "La Maladie d'amour & Être une femme",
    "Je vais t'aimer & Le France",
    "Je l'aime à mourir & La Corrida",
    'Petite Marie & Sarbacane',
    'Mistral gagnant & Morgane de toi',
    'Laisse béton & Dès que le vent soufflera',
    'Trois nuits par semaine & Canary Bay',
    'Formidable & Tous les mêmes',
    "Santé & L'Enfer",
    "Alexandrie Alexandra & Comme d'habitude",
    'Le téléphone pleure & Magnolias for ever',
    'Cette année-là & Belinda',
    "Les Champs-Élysées & L'Été indien",
    "Et si tu n'existais pas & À toi",
    'Siffler sur la colline & Salut les amoureux',
    "Le Chanteur & SOS d'un terrien en détresse",
    "L'Aziza & Tous les cris les SOS",
    "Ella elle l'a & Résiste",
    'Il jouait du piano debout & Babacar',
    'La Javanaise & Le Poinçonneur des Lilas',
    "Paroles paroles & Gigi l'amoroso",
    'Laissez-moi danser & Mourir sur scène',
    'Libertine & Désenchantée',
    'Je veux & On ira',
    "Il est où le bonheur & On s'attache",
    'En apesanteur & Un jour au mauvais endroit',
    'Casser la voix & Place des grands hommes',
    "Je m'en vais & Pas là",
    'Balance ton quoi & Tout oublier',
    'Djadja & Pookie',
    'Cosmo & En feu',
    'Andalouse & Color Gitano',
    'Marcia Baila & Andy',
    'Un autre monde & Cendrillon',
    'Le vent nous portera & Tostaky',
    'Foule sentimentale & Allo maman bobo',
    'La Groupie du pianiste & Seras-tu là',
    'Ma préférence & Femmes je vous aime',
    "La Dernière Séance & Couleur menthe à l'eau",
    'Et moi et moi et moi & Les Cactus',
    "Les Copains d'abord & La Mauvaise Réputation",
    "Le Gorille & Chanson pour l'Auvergnat",
    "L'Aigle noir & Göttingen",
    "La Mer & Y'a d'la joie",
    'Les Feuilles mortes & À bicyclette',
    "Syracuse & Jardin d'hiver",
    'Le Sud & Mirza',
    'On ira tous au paradis & Love me please love me',
    "L'École est finie & Spacer",
    'Joe le taxi & Be my baby',
    'Lucie & Fan',
    'Savoir aimer & Ma liberté de penser',
    'Nathalie & Et maintenant',
    'Santiano & Céline',
    'Relax & Grace Kelly',
    'Mamma Mia & Dancing Queen',
    'Waterloo & Fernando',
    'Yesterday & Let it be',
    'Hey Jude & Help',
    'Bohemian Rhapsody & We will rock you',
    'Thriller & Billie Jean',
    'Beat it & Bad',
    'Like a virgin & La Isla Bonita',
    'Love me tender & Jailhouse Rock',
    'No woman no cry & Could you be loved',
    'Hello & Skyfall',
    'Umbrella & Diamonds',
    "Stayin' alive & How deep is your love",
    'Get lucky & One more time',
    'Yellow & Viva la vida',
    'Rocket Man & Your song',
    'In the air tonight & Another day in paradise',
    'The Best & Proud Mary',
    'I will always love you & I wanna dance with somebody',
    'What a wonderful world & Hello Dolly',
    'My way & Strangers in the night',
    'Smells like teen spirit & Come as you are',
    'Dernière danse & Tourner dans le vide',
    'Aline & Les Mots bleus',
    "Sur la route & J'en veux encore",
    "Lambé an dro & L'Apologie",
    "L'Hymne de nos campagnes & Serre-moi",
    "Le Dîner & L'Effet papillon",
    "Voilà c'est fini & Temps à nouveau",
    'Butterfly & Lola',
    'Bouge de là & Caroline',
    'Je danse le Mia & Petit frère',
    'Basique & La Pluie',
    'La Grenade & Le Reste',
    'Ma philosophie & Ne retiens pas tes larmes',
    "Au soleil & J'attends l'amour",
    'Tri Martolod & Juste pour me souvenir',
    "Une belle histoire & Fais comme l'oiseau",
    "Laisse-moi t'aimer & Qui saura",
    'Capitaine abandonné & Plus près des étoiles',
    'Nuit de folie & La Vie la nuit',
    'La Bohème & For me formidable',
    'Gabrielle & Quelque chose de Tennessee',
    "Comme d'habitude & Le Lundi au soleil",
    "L'Été indien & Le Petit Pain au chocolat",
    'Ma Gueule & Diego libre dans sa tête',
    'Résiste & Évidemment',
    "Allumer le feu & Que je t'aime",
    'La Bohème & Emmenez-moi',
    "L'aventurier & J'ai demandé à la lune",
    'Alors on danse & Papaoutai',
    "La maladie d'amour & En chantant",
    'Alexandrie Alexandra & Le lundi au soleil',
    "Je l'aime à mourir & Petite Marie",
    'Mistral gagnant & Laisse béton',
  ]),
  ...group('Chanson', [
    'Au clair de la lune',
    'Une souris verte',
    'Il était un petit navire',
    "Sur le pont d'Avignon",
    'Promenons-nous dans les bois',
    'Alouette gentille alouette',
    'Ah les crocodiles',
    'Il court il court le furet',
    'Meunier tu dors',
    "J'ai du bon tabac",
    'Petit papa Noël',
    'Vive le vent',
    'Mon beau sapin',
    'À la claire fontaine',
    'Dans la forêt lointaine',
    'Savez-vous planter les choux',
    'Le Petit Bonhomme en mousse',
    'La Danse des canards',
    'Le Lion est mort ce soir',
    'Tout va très bien madame la marquise',
    'Le Bal masqué',
    'Il en faut peu pour être heureux',
    'Je voudrais déjà être roi',
    'Ce rêve bleu',
    'Un jour mon prince viendra',
    'Siffler en travaillant',
    'Les Rois du monde',
    'Le Temps des cathédrales',
    'Les Démons de minuit',
    'Ça plane pour moi',
    'Une poule sur un mur',
    "Pomme de reinette et pomme d'api",
    'Trois petits chats',
    'Ainsi font font font',
    'Le Bon Roi Dagobert',
    "Malbrough s'en va-t-en guerre",
    "Les Petits Poissons dans l'eau",
    'Une chanson douce',
    "Dodo l'enfant do",
    "Fais dodo Colas mon p'tit frère",
    'Mon âne mon âne',
    'Il pleut il pleut bergère',
    'Le Chant des partisans',
    'Le Temps des cerises',
    'Mon amant de Saint-Jean',
    'Femme like you',
    'Les Lacs du Connemara',
    'Tous les garçons et les filles',
    'Je suis malade',
    'Ne me quitte pas',
  ]),
  ...group('Cuisine', [
    'Un gratin dauphinois',
    'Une blanquette de veau',
    'Un bœuf bourguignon',
    'Une tarte Tatin',
    'Une crème brûlée',
    'Une raclette savoyarde',
    'Une fondue savoyarde',
    'Un hachis parmentier',
    'Une quiche lorraine',
    "Une soupe à l'oignon",
    'Des moules frites',
    'Une choucroute garnie',
    'Un cassoulet toulousain',
    'Une ratatouille niçoise',
    'Un clafoutis aux cerises',
    'Une mousse au chocolat',
    'Une île flottante',
    'Des crêpes au sucre',
    'Une galette des rois',
    'Un éclair au café',
    'Une tarte aux pommes',
    'Un gâteau au yaourt',
    'Des œufs à la neige',
    'Un poulet rôti',
    'Une omelette aux champignons',
    'Une salade niçoise',
    'Un steak frites',
    'Un plateau de fromages',
    'Une pizza quatre fromages',
    'Des spaghettis bolognaise',
    'Des lasagnes à la bolognaise',
    'Un couscous royal',
    'Une paella aux fruits de mer',
    'Un tajine aux pruneaux',
    'Des escargots de Bourgogne',
    'Un magret de canard',
    'Du foie gras',
    'Une potée auvergnate',
    'Un far breton',
    'Des madeleines de Commercy',
    'Une tarte au citron meringuée',
    'Un fondant au chocolat',
    'Un baba au rhum',
    'Une charlotte aux fraises',
    'Un gâteau de riz',
    'Une religieuse au chocolat',
    'Une gaufre à la chantilly',
    'Un pain au chocolat',
    'Un croissant au beurre',
    'Une baguette de pain',
    'Un sandwich jambon beurre',
    'Une soupe de légumes',
    'Une purée de pommes de terre',
    'Des frites maison',
    "Un gigot d'agneau",
    'Une côte de bœuf',
    'Un tartare de saumon',
    'Une brandade de morue',
    'Une salade de fruits',
    'Une compote de pommes',
    'Un yaourt nature',
    'Une pâte à tartiner',
    'Blanquette de veau',
    'Tarte aux pommes',
    'Mousse au chocolat',
    'Une tartine de confiture',
    'Un œuf à la coque',
  ]),
  ...group('Lieu', [
    'La tour Eiffel',
    'Le château de Versailles',
    'La place de la Concorde',
    "L'Arc de triomphe",
    'La cathédrale Notre-Dame',
    'Le musée du Louvre',
    'La gare de Lyon',
    'Le jardin du Luxembourg',
    'La salle de bains',
    'La cour de récréation',
    'Le marché du dimanche',
    'La boulangerie du coin',
    'Le cinéma du quartier',
    'La piscine municipale',
    'La plage de sable fin',
    'Le sommet de la montagne',
    'Le fond de la mer',
    'La forêt enchantée',
    "Le parc d'attractions",
    'La fête foraine',
    'La station de ski',
    'Le terrain de foot',
    'La salle des fêtes',
    'La mairie du village',
    'La bibliothèque municipale',
    'La maison de retraite',
    'Le bureau de poste',
    'La caserne des pompiers',
    'Le commissariat de police',
    "La salle d'attente",
    'Le cabinet du dentiste',
    'Le centre commercial',
    'Le quai de la gare',
    "La cabine d'essayage",
    'Le grenier de mamie',
    'La cave à vin',
    'Le jardin potager',
    'La cabane au fond du jardin',
    'Le camping municipal',
    "La chambre d'hôtel",
    'Le mont Saint-Michel',
    "La Côte d'Azur",
  ]),
  ...group('Objet', [
    'Une brosse à dents',
    'Un fer à repasser',
    'Une machine à laver',
    'Un téléphone portable',
    'Un ordinateur portable',
    'Une lampe de poche',
    'Une boîte aux lettres',
    'Un rouleau à pâtisserie',
    'Une montre à gousset',
    'Un trousseau de clés',
    'Un sac à dos',
    'Une valise à roulettes',
    'Une paire de lunettes',
    'Une règle graduée',
    'Un cahier à spirale',
    "Une trousse d'écolier",
    'Un stylo plume',
    'Une paire de ciseaux',
    'Un rouleau de scotch',
    'Une boîte à outils',
    'Une tondeuse à gazon',
    'Une bougie parfumée',
    'Un cadre photo',
    'Un ballon de baudruche',
    'Une boule à neige',
    'Un appareil photo',
    'Une guirlande lumineuse',
    'Une montre en or',
    'Un réveil qui sonne',
    'Une machine à coudre',
    'Une lampe de chevet',
    'Un bâton de rouge à lèvres',
    'Une boîte de mouchoirs',
    'Un sac de couchage',
    'Une tente de camping',
    'Un ballon de football',
    'Une raquette de tennis',
    'Une table de chevet',
  ]),
  ...group('Animal', [
    "Un éléphant d'Afrique",
    'Un crocodile du Nil',
    'Un ours polaire',
    'Un panda géant',
    'Une baleine bleue',
    'Un requin blanc',
    'Une tortue de mer',
    'Un poisson rouge',
    'Un flamant rose',
    'Un manchot empereur',
    'Un hibou grand-duc',
    'Un aigle royal',
    'Un coq gaulois',
    'Une poule pondeuse',
    'Un canard colvert',
    'Un lapin de garenne',
    'Un écureuil roux',
    'Un renard roux',
    'Un loup gris',
    'Un berger allemand',
    'Un chat de gouttière',
    "Un cochon d'Inde",
    'Un ver de terre',
    'Un serpent à sonnette',
    'Un chien qui remue la queue',
    'Un chat qui ronronne',
    'Une vache dans un pré',
    'Un troupeau de moutons',
    "Un essaim d'abeilles",
    'Une meute de loups',
    'Un banc de poissons',
    'Une nuée de criquets',
    'Le roi des animaux',
    "Le meilleur ami de l'homme",
    'Une vache normande',
    'Un chien de berger',
  ]),
  ...group('Sport', [
    'Le Tour de France',
    'La Coupe du monde de football',
    'Les Jeux olympiques',
    'Le tournoi des Six Nations',
    'Les Vingt-Quatre Heures du Mans',
    'Le saut à la perche',
    'Le lancer de javelot',
    'Le saut en hauteur',
    'Le saut en longueur',
    'Le cent mètres',
    'Le marathon de Paris',
    'La natation synchronisée',
    'Le patinage artistique',
    'Le ski de fond',
    'Le saut à ski',
    'La planche à voile',
    'Le tennis de table',
    'La boxe anglaise',
    "Le tir à l'arc",
    'Un but en pleine lucarne',
    'Un carton rouge',
    'Un penalty raté',
    "Une médaille d'or olympique",
    'Le maillot jaune',
    'Une partie de pétanque',
    'Un match de tennis',
    'La finale de la Coupe du monde',
    'Un coup franc direct',
    'Un plongeon de haut vol',
  ]),
  ...group('Métier', [
    'Un médecin généraliste',
    'Un professeur des écoles',
    'Un pilote de ligne',
    "Une hôtesse de l'air",
    'Un chauffeur de taxi',
    'Le boulanger du village',
    'Une dame de la cantine',
    'Un moniteur de ski',
    'Un maître nageur sauveteur',
    'Un chef étoilé',
    'Un garde forestier',
    'Un gardien de phare',
    'Un dresseur de lions',
    'Un clown de cirque',
    'Un chauffeur de bus',
    'Un contrôleur de train',
    'Un agent de la circulation',
    'Un ramoneur sur le toit',
    'Un livreur de pizzas',
    'Un vendeur de glaces',
    'Un chirurgien du cœur',
    'Un professeur de piano',
    "Une maîtresse d'école",
    'Un chef cuisinier',
  ]),
  ...group('Pays', [
    "L'Afrique du Sud",
    'Le pays du Soleil-Levant',
    'Le plat pays de Brel',
    'La République tchèque',
    'Les îles Canaries',
    'Les îles Baléares',
    'La Corée du Sud',
    'Le Costa Rica',
    "La Côte d'Ivoire",
    "Les États-Unis d'Amérique",
  ]),
  ...group('Personnage', [
    'Le Petit Chaperon rouge',
    'Le Grand Méchant Loup',
    'Le Chat botté',
    'Le Petit Poucet',
    "Boucle d'or et les trois ours",
    'Hansel et Gretel',
    'Le Père Noël',
    'La Petite Souris',
    'Le Lapin de Pâques',
    'Robin des Bois',
    'Le Capitaine Crochet',
    'La Fée Clochette',
    'Le Chapelier fou',
    'Le Lapin blanc',
    'Le Commissaire Maigret',
    'Obélix et Idéfix',
    'Le Capitaine Haddock',
    'Tintin et Milou',
    'Le Professeur Tournesol',
    'Spirou et Fantasio',
    'Le Schtroumpf grognon',
    'Le Grand Schtroumpf',
    'Gargamel et Azraël',
    'La Princesse Leia',
    'Gandalf le Gris',
    "Le Fantôme de l'Opéra",
    'Cendrillon et sa pantoufle de verre',
    'Le Prince charmant',
    'La Bonne Fée',
    "La Sorcière de l'Ouest",
    'Le Bonhomme de neige',
    'Le Bonhomme Carnaval',
  ]),
  ...group('Personnage historique', [
    'Léonard de Vinci',
    'Jean de La Fontaine',
    'Charles de Gaulle',
    'Martin Luther King',
    'Wolfgang Amadeus Mozart',
    'Ludwig van Beethoven',
    'Vincent van Gogh',
    'Alexandre le Grand',
    'Guillaume le Conquérant',
    'Le petit caporal',
    'Le roi Louis Seize',
    'La reine Victoria',
    "L'empereur Napoléon Trois",
    'Le général de Gaulle',
    'Les chevaliers de la Table ronde',
    'Le baron Haussmann',
    'Le docteur Guillotin',
    'Les frères Lumière',
    'Les frères Montgolfier',
    'Christophe Colomb en Amérique',
  ]),
  ...group('Ville', [
    'Rio de Janeiro',
    'La Ville lumière',
    'La Cité des papes',
    'La ville rose',
    'La capitale des Gaules',
    'La Grosse Pomme',
    'La Cité des anges',
    'La ville éternelle',
    'Une balade sur les quais de Seine',
    'Un week-end à Venise',
    'Une croisière sur le Nil',
    'Un voyage à New York',
    "Les canaux d'Amsterdam",
    'Le carnaval de Venise',
    'La fête des Lumières de Lyon',
  ]),
  ...group('Monument', [
    'La tour de Pise',
    'Le Colisée de Rome',
    'La statue de la Liberté',
    'Les pyramides de Gizeh',
    'La Grande Muraille de Chine',
    'Le Taj Mahal',
    'Le Machu Picchu',
    'Le pont du Gard',
    'Le château de Chambord',
    'Le château de Chenonceau',
    'La Sagrada Família',
    'Le pont de Brooklyn',
    'Le Golden Gate',
    "L'Opéra de Sydney",
    'Le Christ rédempteur',
    'La porte de Brandebourg',
    'La tour de Londres',
    'Le palais de Buckingham',
    'La Pyramide du Louvre',
    'Le viaduc de Millau',
  ]),
  ...group('Fruit et légume', [
    'Une pomme golden',
    'Une poire williams',
    'Une fraise des bois',
    'Une pêche de vigne',
    'Un melon charentais',
    'Une noix de coco',
    'Une orange sanguine',
    'Un citron vert',
    'Un raisin muscat',
    'Un poivron rouge',
    'Une tomate cerise',
    'Un chou de Bruxelles',
    'Un haricot vert',
    'Un petit pois',
    'Une pomme de terre',
    'Un champignon de Paris',
    "Une gousse d'ail",
  ]),
  ...group('Instrument', [
    'Un piano à queue',
    'Une guitare électrique',
    'Une guitare sèche',
    'Une flûte traversière',
    'Une flûte à bec',
    'Un trombone à coulisse',
    'Un cor de chasse',
    'Un piano désaccordé',
    "Le violon d'Ingres",
    'Une guitare à douze cordes',
    'Un orgue de Barbarie',
    'Une boîte à musique',
    'Un tambour de fanfare',
    'Un orchestre symphonique',
    'Une fanfare municipale',
  ]),
  ...group('Vêtement', [
    'Un pull en laine',
    'Un jean délavé',
    'Une chemise à carreaux',
    'Une robe de soirée',
    'Une jupe plissée',
    'Un short de bain',
    'Un maillot de bain',
    'Une veste en cuir',
    "Un manteau d'hiver",
    'Un ciré jaune',
    'Une paire de gants',
    'Un chapeau de paille',
    'Un béret basque',
    'Un nœud papillon',
    'Des bottes de pluie',
    'Une robe de chambre',
    'Un costume trois pièces',
    'Un kilt écossais',
    'Un tablier de cuisine',
  ]),
  ...group('Dans la maison', [
    'La table de la cuisine',
    'Le canapé du salon',
    'Le lit superposé',
    'La table de chevet',
    'Le four à micro-ondes',
    'La boîte à chaussures',
    'Le placard à balais',
    'La table à repasser',
    "L'étendoir à linge",
    'Le panier à linge',
    'Le tapis du salon',
  ]),
  ...group('Nature', [
    'Un coucher de soleil',
    'Un lever de soleil',
    "Une pluie d'étoiles filantes",
    'Une aurore boréale',
    "Un orage d'été",
    'Un coup de tonnerre',
    'Une tempête de neige',
    'Un flocon de neige',
    'Une goutte de rosée',
    'Un torrent de montagne',
    'Un lac de montagne',
    'Une prairie fleurie',
    'Un champ de blé',
    'Un champ de tournesols',
    'Un champ de lavande',
    'Une forêt de sapins',
    'Un chêne centenaire',
    'Un saule pleureur',
    'Une rose rouge',
    'Un trèfle à quatre feuilles',
    'Un volcan en éruption',
    'Une plage de sable blanc',
    'Une étoile de mer',
    'Une marée basse',
    'Une vague géante',
    'Un désert de sable',
  ]),
  ...group('Véhicule', [
    'Une voiture de course',
    'Une voiture de police',
    'Un camion de pompiers',
    'Un train à grande vitesse',
    'Une locomotive à vapeur',
    'Un avion de ligne',
    'Une soucoupe volante',
    'Un bateau à moteur',
    'Le train de nuit',
    'Un bateau de pêche',
    'La navette spatiale',
    'Le carrosse de Cendrillon',
    'La coccinelle de Volkswagen',
    'Un autobus à impériale',
    'Un camion de déménagement',
    'La voiture de mariés',
  ]),
  ...group('Jeu de société', [
    'Le Trivial Pursuit',
    'Le jeu des sept familles',
    "Le jeu de l'oie",
    'Les petits chevaux',
    "Le jeu d'échecs",
    'Le jeu de dames',
    'Le Puissance quatre',
    'La bataille navale',
    'Le Mille Bornes',
    "Le Time's Up",
    'Le Jungle Speed',
    'Le Qui est-ce',
    'Les Colons de Catane',
    'Les Aventuriers du rail',
    'Le Docteur Maboul',
  ]),
  ...group('Fête', [
    'Le réveillon de Noël',
    "Le jour de l'An",
    'La galette des rois',
    "Le poisson d'avril",
    'La chasse aux œufs de Pâques',
    'La fête des Mères',
    'La fête des Pères',
    'La fête de la Musique',
    'Le quatorze Juillet',
    "Le feu d'artifice",
    'Le bal des pompiers',
    'Le marché de Noël',
    'Un anniversaire surprise',
    'Une pendaison de crémaillère',
    'Un enterrement de vie de garçon',
    'La fête des voisins',
    'Le carnaval de Nice',
    'Le carnaval de Rio',
    'Le Nouvel An chinois',
  ]),
  ...group('Super-héros', [
    'Les Quatre Fantastiques',
    'Le Silver Surfer',
    'Les Gardiens de la Galaxie',
    "L'homme de fer",
    'La femme chat',
    'Le chevalier noir de Gotham',
    'Le dieu du tonnerre',
    'Le géant vert',
    'La ligue des justiciers',
  ]),
  ...group('Livre', [
    'Notre-Dame de Paris',
    'Vingt Mille Lieues sous les mers',
    'Le Tour du monde en quatre-vingts jours',
    'Voyage au centre de la Terre',
    'Le Rouge et le Noir',
    'Le Père Goriot',
    'Les Fables de La Fontaine',
    'Le Malade imaginaire',
    'Le Bourgeois gentilhomme',
    'Roméo et Juliette',
    "L'Île au trésor",
    'Les Contes de Perrault',
    'Le Vieil Homme et la Mer',
    'Orgueil et Préjugés',
    'Les Hauts de Hurlevent',
    "Le Journal d'Anne Frank",
    'Le Grand Meaulnes',
    'Les Liaisons dangereuses',
  ]),
  ...group('Corps humain', [
    'Le petit doigt',
    'Le gros orteil',
    'La plante des pieds',
    'Le dos de la main',
    "La pomme d'Adam",
    "Le lobe de l'oreille",
    'Le bout du nez',
    'La colonne vertébrale',
    'La cage thoracique',
    'Les dents de sagesse',
    'Les cheveux bouclés',
  ]),
  ...group('Boisson', [
    'Un café crème',
    'Un chocolat chaud',
    'Un thé à la menthe',
    "Un jus d'orange pressé",
    'Un diabolo menthe',
    'Un sirop de grenadine',
    'Un verre de lait',
    "Une bouteille d'eau",
    'Une eau pétillante',
    'Un verre de vin rouge',
    'Une coupe de champagne',
    'Un cidre brut',
    'Une bière pression',
    'Un kir royal',
    'Une piña colada',
    'Un vin chaud',
    'Un lait fraise',
  ]),
  ...group('Jeu vidéo', [
    'Super Mario Bros',
    'The Legend of Zelda',
    'Sonic le hérisson',
    'Call of Duty',
    'Prince of Persia',
    'Grand Theft Auto',
    'Red Dead Redemption',
    'Super Smash Bros',
    'Mario et Luigi',
    'La princesse Peach',
    'Le plombier moustachu',
    'Les lapins crétins',
    'Un casque de réalité virtuelle',
    'Une manette de console',
    'Une partie de Tetris',
    'Un combat de boss final',
  ]),
];
