import { group, type Phrase } from './theme';

/** Toss-up puzzles: three words at most, so that a team can buzz quickly. */
export const TOSS_UP_PHRASES: readonly Phrase[] = [
  ...group('Expression', [
    'Coup de foudre',
    'Bouche cousue',
    'Prendre la porte',
    'Tomber à pic',
    'Rire aux éclats',
    'Tenir parole',
    'Perdre pied',
    "Prendre l'air",
    'Faire mouche',
    'Bouche bée',
    'Coup de pouce',
    'Coup de théâtre',
    'Coup de bol',
    'Faire la fête',
    'Avoir du flair',
    'Au pied levé',
    'Haut la main',
    'Clé en main',
    'Mot de passe',
    'Sain et sauf',
    'Bon débarras',
    'Bon appétit',
    'Bonne nuit',
    'Petit à petit',
    'Coûte que coûte',
    'Tant pis',
    'Tant mieux',
    'Pile poil',
    'Nickel chrome',
    "Cœur d'artichaut",
    'Fin gourmet',
    'Fin limier',
    'Belle lurette',
    'Tirer au flanc',
    'Mettre le paquet',
    'Faire la moue',
    'Lever le coude',
    'Avoir la bougeotte',
    'Mettre les voiles',
    'Tenir bon',
    'Rire jaune',
    'Prendre racine',
  ]),
  ...group('Cuisine', [
    'Soupe de poisson',
    'Tarte au citron',
    'Crêpe Suzette',
    'Pain perdu',
    'Œuf mollet',
    'Œufs brouillés',
    'Poulet basquaise',
    'Canard laqué',
    'Salade César',
    'Hamburger',
    'Pâtes carbonara',
    'Risotto aux cèpes',
    'Sushi',
    'Nems',
    'Tiramisu',
    'Panna cotta',
    'Macaron',
    'Meringue',
    'Chouquette',
    'Brioche',
    "Pain d'épices",
    'Nougat',
    'Calisson',
    'Barbe à papa',
    "Pomme d'amour",
    'Churros',
    'Beignet',
    'Bugne',
    'Cannelé',
    'Financier',
    'Palmier',
    'Sablé breton',
    'Galette bretonne',
    'Rillettes',
    'Le cassoulet',
    'La ratatouille',
    'Un pot-au-feu',
    'Un croque-madame',
    'Une bouillabaisse',
    'Un paris-brest',
    'Un millefeuille',
    'Une tartiflette',
    'Un aligot',
    'Un kouign-amann',
    'Une forêt-noire',
    'Des profiteroles',
    'Une chocolatine',
    'Bœuf bourguignon',
    'Gratin dauphinois',
    'Crêpes Suzette',
  ]),
  ...group('Animal', [
    'Mille-pattes',
    'Libellule',
    'Sauterelle',
    'Grillon',
    'Luciole',
    'Moustique',
    'Bourdon',
    'Guêpe',
    'Frelon',
    'Chauve-souris',
    'Taupe',
    'Musaraigne',
    'Belette',
    'Blaireau',
    'Loutre',
    'Castor',
    'Raton laveur',
    'Mouffette',
    'Lama',
    'Dromadaire',
    'Zèbre',
    'Gazelle',
    'Antilope',
    'Guépard',
    'Léopard',
    'Puma',
    'Lynx',
    'Ocelot',
    'Tigre du Bengale',
    'Panthère noire',
    'Gorille',
    'Orang-outan',
    'Ouistiti',
    'Paresseux',
    'Tatou',
    'Fourmilier',
    'Morse',
    'Otarie',
    'Orque',
    'Narval',
    'Raie manta',
    'Poisson-clown',
    'Anguille',
    'Méduse',
    'Langouste',
    'Crevette',
    'Crabe',
    'Oursin',
    'Moule',
    'Huître',
    'Calamar',
    'Un saint-bernard',
    'Une chauve-souris',
    'Une girafe',
    'Un hippopotame',
    'Un rhinocéros',
    'Un kangourou',
    'Un koala',
    'Un ornithorynque',
    'Un dauphin',
    'Une pieuvre',
    'Un perroquet',
    'Un pélican',
    'Un pingouin',
    'Une chouette',
    'Un hérisson',
    'Un sanglier',
    'Un cerf',
    'Une biche',
    'Un chamois',
    'Une marmotte',
    'Un labrador',
    'Un caniche',
    'Un hamster',
    'Une coccinelle',
    'Un papillon',
    'Une abeille',
    'Une fourmi',
    'Une araignée',
    'Un escargot',
    'Une limace',
    'Une grenouille',
    'Un caméléon',
  ]),
  ...group('Objet', [
    'Ballon rouge',
    'Boule de bowling',
    'Brosse à cheveux',
    'Peigne',
    'Savon de Marseille',
    'Gant de toilette',
    'Serviette de bain',
    'Coton-tige',
    'Pince à linge',
    'Porte-clés',
    'Lampe torche',
    'Boussole',
    'Jumelles',
    'Loupe',
    'Sablier',
    'Métronome',
    'Globe terrestre',
    'Mappemonde',
    'Dictionnaire',
    'Agenda',
    'Calendrier',
    "Carnet d'adresses",
    'Enveloppe',
    'Timbre-poste',
    'Carte postale',
    'Pot de colle',
    'Pinceau',
    'Chevalet',
    'Palette de peintre',
    'Craie',
    'Tableau noir',
    'Cartable',
    'Équerre',
    'Rapporteur',
    'Calculatrice',
    'Clé USB',
    'Casque audio',
    'Écouteurs',
    'Chargeur',
    'Un sèche-cheveux',
    'Un presse-agrumes',
    'Une lampe torche',
    'Un réveil-matin',
    'Un aspirateur',
    'Une télécommande',
    'Un parapluie',
    'Un tire-bouchon',
    'Un ouvre-boîte',
    'Une passoire',
    'Une cocotte-minute',
    'Un grille-pain',
    'Une cafetière',
    'Une bouilloire',
    'Un porte-monnaie',
    'Un taille-crayon',
    'Une gomme',
    'Une agrafeuse',
    'Un trombone',
    'Un tournevis',
    'Une perceuse',
    'Un marteau',
    'Une échelle',
    'Une brouette',
    'Un arrosoir',
    'Un barbecue',
    'Un miroir',
    'Un coussin',
    'Une couverture',
    'Un oreiller',
    'Un cerf-volant',
    'Une tirelire',
  ]),
  ...group('Fruit et légume', [
    'Litchi',
    'Kaki',
    'Grenade',
    'Groseille',
    'Cassis',
    'Mûre',
    'Airelle',
    'Nectarine',
    'Brugnon',
    'Patate douce',
    'Topinambour',
    'Panais',
    'Rutabaga',
    'Fenouil',
    'Céleri',
    'Endive',
    'Épinard',
    'Blette',
    'Mâche',
    'Roquette',
    'Cresson',
    'Chou rouge',
    'Chou kale',
    'Gingembre',
    'Piment',
    'Une banane',
    'Une framboise',
    'Une myrtille',
    'Une cerise',
    'Un abricot',
    'Une pastèque',
    'Un ananas',
    'Une mangue',
    'Une clémentine',
    'Un pamplemousse',
    'Une figue',
    'Une prune',
    'Une mirabelle',
    'Une carotte',
    'Un poireau',
    'Un navet',
    'Une courgette',
    'Une aubergine',
    'Un concombre',
    'Une laitue',
    'Un chou-fleur',
    'Un brocoli',
    'Un potiron',
    'Une citrouille',
    'Un radis',
    'Une betterave',
    'Un artichaut',
    'Une asperge',
    'Un oignon',
    'Une échalote',
  ]),
  ...group('Personnage', [
    'Le Père Fouettard',
    'Barbe bleue',
    "Peau d'âne",
    'Gepetto',
    'Jiminy Cricket',
    'Tarzan',
    'Bagheera',
    'Shere Khan',
    'Simba',
    'Nala',
    'Timon et Pumbaa',
    'Scar',
    'Ariel',
    'Ursula',
    'Sébastien le crabe',
    'Elsa',
    'Anna',
    'Kristoff',
    'Woody',
    "Buzz l'Éclair",
    'Nemo',
    'Rémy le rat',
    'Shrek',
    "L'âne",
    'Le Chat Potté',
    'Gru',
    "Bob l'éponge",
    "Patrick l'étoile",
    'Garfield',
    'Snoopy',
    'Charlie Brown',
    'Popeye',
    'Blanche-Neige',
    'Peter Pan',
    'Sherlock Holmes',
    'Arsène Lupin',
    'Hercule Poirot',
    'James Bond',
    'Lucky Luke',
    'Les Dalton',
    'Gaston Lagaffe',
    'Le Marsupilami',
    'Mickey Mouse',
    'Minnie Mouse',
    "Winnie l'ourson",
    'Luke Skywalker',
    'Maître Yoda',
    'Harry Potter',
    'Hermione Granger',
    'Albus Dumbledore',
    'Frodon Sacquet',
    'Don Quichotte',
    'Quasimodo',
    'Esmeralda',
    'Jean Valjean',
    'Cosette',
    "D'Artagnan",
  ]),
  ...group('Métier', [
    'Pompier',
    'Facteur',
    'Plombier',
    'Électricien',
    'Coiffeuse',
    'Infirmière',
    'Docteur',
    'Chirurgien',
    'Ostéopathe',
    'Opticien',
    'Pharmacienne',
    'Astronome',
    'Archéologue',
    'Paléontologue',
    'Géologue',
    'Météorologue',
    'Cascadeur',
    'Comédien',
    'Chanteuse',
    'Danseuse étoile',
    'Jongleur',
    'Acrobate',
    'Dompteur',
    'Ventriloque',
    'Peintre',
    'Sculpteur',
    'Potier',
    'Un boulanger',
    'Une infirmière',
    'Un pâtissier',
    'Un boucher',
    'Un fromager',
    'Un poissonnier',
    'Un fleuriste',
    'Un coiffeur',
    'Un policier',
    'Un gendarme',
    'Un dentiste',
    'Un vétérinaire',
    'Un infirmier',
    'Un pharmacien',
    'Un instituteur',
    'Un architecte',
    'Un menuisier',
    'Un charpentier',
    'Un maçon',
    'Un jardinier',
    'Un agriculteur',
    'Un apiculteur',
    'Un vigneron',
    'Un pêcheur',
    'Un marin',
    'Un astronaute',
    'Un journaliste',
    'Un photographe',
    'Un cuisinier',
    'Un serveur',
    'Un sommelier',
    'Un avocat',
    'Un juge',
    'Un notaire',
    'Un banquier',
    'Un comptable',
    'Un informaticien',
    'Un mécanicien',
    'Un horloger',
    'Un bijoutier',
    'Un libraire',
    'Un bibliothécaire',
    'Une sage-femme',
  ]),
  ...group('Sport', [
    'Curling',
    'Bobsleigh',
    'Biathlon',
    'Luge',
    'Patinage de vitesse',
    'Hockey sur glace',
    'Ski alpin',
    'Slalom géant',
    'Descente',
    'Plongée sous-marine',
    'Aviron',
    'Canoë-kayak',
    'Voile',
    'Ping-pong',
    'Squash',
    'Pelote basque',
    'Lutte',
    'Sumo',
    'Haltérophilie',
    'Lancer du poids',
    'Lancer du disque',
    'Course de haies',
    'Relais',
    'Décathlon',
    'Heptathlon',
    'Pentathlon moderne',
    'Skateboard',
    'Roller',
    'Trampoline',
    'Parachutisme',
    'Parapente',
    'Deltaplane',
    'Spéléologie',
    'Alpinisme',
    'Billard',
    'Fléchettes',
    'Bowling',
    'Quilles',
    'Croquet',
    'La pétanque',
    'Le ski nautique',
    'Coupe du monde',
    'Roland-Garros',
    'Le snowboard',
    'Le surf',
    'Le kitesurf',
    "L'escalade",
    'La randonnée',
    'Le badminton',
    'Le handball',
    'Le basket-ball',
    'Le volley-ball',
    'Le water-polo',
    'Le rugby',
    'Le golf',
    "L'équitation",
    "L'escrime",
    'Le judo',
    'Le karaté',
    'Le cyclisme',
    'Le triathlon',
    'La gymnastique',
  ]),
  ...group('Jeu de société', [
    'Morpion',
    'Pierre feuille ciseaux',
    'Cache-cache',
    'Colin-maillard',
    'Chat perché',
    'Marelle',
    'Corde à sauter',
    'Billes',
    'Osselets',
    'Toupie',
    'Bilboquet',
    'Cerceau',
    'Loto',
    'Tombola',
    'Mots croisés',
    'Mots fléchés',
    'Puzzle',
    "Rubik's Cube",
    'Dés',
    'Carte joker',
    'As de pique',
    'Roi de cœur',
    'Dame de trèfle',
    'Valet de carreau',
    'Le Monopoly',
    'Le Scrabble',
    'Le Cluedo',
    'Le Uno',
    'Le tarot',
    'La belote',
    'Le poker',
    'Le domino',
    'Le Pictionary',
    'Le Dixit',
    'Les Loups-garous',
    'Le Dobble',
    'Le Mikado',
    'Le Jenga',
    'Le Twister',
    'Le Risk',
    "Le Yam's",
    'Le Rummikub',
    'Le Labyrinthe',
    'Le Memory',
  ]),
  ...group('Nature', [
    'Arc-en-ciel',
    'Brouillard',
    'Bruine',
    'Grêle',
    'Verglas',
    'Givre',
    'Tempête',
    'Ouragan',
    'Tornade',
    'Tsunami',
    'Séisme',
    'Avalanche',
    'Glissement de terrain',
    'Marée haute',
    'Pleine lune',
    'Croissant de lune',
    'Étoile du Berger',
    'Voie lactée',
    'Grande Ourse',
    'Petite Ourse',
    'Comète',
    'Météorite',
    'Éclipse solaire',
    'Nuage de pluie',
    'Ciel étoilé',
    'Rosée du matin',
    'Feuille morte',
    'Bourgeon',
    "Brin d'herbe",
    "Toile d'araignée",
    'Un éclair',
    'Une cascade',
    'Une rivière',
    'Un cactus',
    'Une marguerite',
    'Un coquelicot',
    'Un tournesol',
    'Un pissenlit',
    'Un coquillage',
    'Un glacier',
    'Une oasis',
    'Une grotte',
  ]),
  ...group('Fête', [
    'Bûche de Noël',
    'Sapin de Noël',
    'Chaussettes de Noël',
    "Calendrier de l'Avent",
    'Fève',
    'Couronne des rois',
    'Œuf en chocolat',
    'Cloches de Pâques',
    'Lapin en chocolat',
    "Citrouille d'Halloween",
    'Bonbons ou sort',
    'Masque de carnaval',
    'Confettis',
    'Serpentins',
    'Cotillons',
    "Gâteau d'anniversaire",
    "Bougies d'anniversaire",
    'Pièce montée',
    'Robe de mariée',
    'Lancer de riz',
    'Dragées',
    'La Chandeleur',
    'Mardi gras',
    'La Saint-Valentin',
    'Halloween',
    'La Toussaint',
    'La Saint-Nicolas',
    'Un mariage',
    'Un baptême',
  ]),
  ...group('Dans la maison', [
    "Porte d'entrée",
    'Interrupteur',
    'Prise électrique',
    'Ampoule',
    'Lustre',
    'Tabouret',
    'Fauteuil',
    'Rocking-chair',
    'Pouf',
    'Étagère',
    'Tiroir',
    'Buffet',
    'Vaisselier',
    'Évier',
    'Robinet',
    'Plan de travail',
    'Hotte aspirante',
    'Plaque de cuisson',
    'Lave-linge',
    'Sèche-linge',
    'Fer à friser',
    'Pèse-personne',
    'Tapis de bain',
    'Rideau de douche',
    'Porte-savon',
    'Cintre',
    'Penderie',
    'Coffre à jouets',
    'Lit à baldaquin',
    "L'armoire normande",
    'La commode',
    'La bibliothèque',
    'Le réfrigérateur',
    'Le congélateur',
    'Le lave-vaisselle',
    'La cheminée',
    'Le radiateur',
    'La baignoire',
    'La douche',
    'Le lavabo',
    'Les toilettes',
    'Le porte-manteau',
    'Le paillasson',
    'La sonnette',
    'La poubelle',
    'Les rideaux',
    'Les volets',
    'La fenêtre',
    "L'escalier",
    'Le grenier',
    'La cave',
    'Le garage',
    'La véranda',
    'La terrasse',
    'Le balcon',
  ]),
  ...group('Boisson', [
    'Grenadine',
    'Orangeade',
    'Citronnade',
    'Thé glacé',
    'Café au lait',
    'Lait chaud',
    'Jus de pomme',
    'Jus de raisin',
    'Eau de coco',
    'Soda',
    'Panaché',
    'Sangria',
    'Rhum arrangé',
    'Armagnac',
    'Chartreuse',
    'Limoncello',
    'Une tisane',
    'Une limonade',
    'Un pastis',
    'Un milk-shake',
    'Un smoothie',
    'Un cappuccino',
    'Un expresso',
  ]),
  ...group('Film', [
    'Les Choristes',
    'Le Corniaud',
    'Titanic',
    'Les Tuche',
    'La Boum',
    'Astérix et Obélix',
    'Les Visiteurs',
    'Intouchables',
    'Jurassic Park',
    'Le Parrain',
    'Indiana Jones',
    'Forrest Gump',
    'Les Bronzés',
    'La Chèvre',
    'Les Compères',
    'Fantômas',
    'Le Prénom',
    'La Haine',
    'Babysitting',
    'Les Profs',
    'Le Placard',
    'Les Randonneurs',
    'Le Hobbit',
    'Avatar',
    'Mission impossible',
    'Mary Poppins',
    'Les Évadés',
    'Le Fugitif',
    'La Momie',
    'SOS Fantômes',
    'Pretty Woman',
    'Dirty Dancing',
    'Grease',
    'Gladiator',
    'Top Gun',
    'Matrix',
    'Inception',
    'Interstellar',
    'Les Misérables',
    'Paddington',
    'Le Bossu',
    "L'Auberge espagnole",
    'Tanguy',
  ]),
  ...group('Lieu', [
    'La Camargue',
    'Le Futuroscope',
    'Le Louvre',
    'Les Calanques',
    'Les Champs-Élysées',
    "L'hôpital",
    'Le supermarché',
    "L'aire d'autoroute",
    'Le péage',
    "L'aéroport",
  ]),
  ...group('Chanson', [
    'Douce France',
    'Je te promets',
    'Tous les mêmes',
    'Joe le taxi',
    'Foule sentimentale',
    'Résiste',
    'Frère Jacques',
    'Joyeux anniversaire',
    'La Marseillaise',
    'Les Sardines',
    'La Chenille',
    'Libérée délivrée',
    "Sous l'océan",
    'Belle',
    'Macarena',
    'La Lambada',
    'Tata Yoyo',
    'Pirouette cacahuète',
    'Petit escargot',
    'Cadet Rousselle',
    'Gentil coquelicot',
    'La Bamba',
    'Bella ciao',
    'Aux Champs-Élysées',
    'Alexandrie Alexandra',
    "L'Aventurier",
    'Hexagone',
    'La Montagne',
    'Emmenez-moi',
  ]),
  ...group('Pays', [
    "L'Australie",
    'Le Portugal',
    'La Norvège',
    'La France',
    "L'Italie",
    "L'Espagne",
    "L'Allemagne",
    'La Belgique',
    'La Suisse',
    'Le Luxembourg',
    'Les Pays-Bas',
    'Le Royaume-Uni',
    "L'Irlande",
    'La Suède',
    'La Finlande',
    'Le Danemark',
    "L'Islande",
    'La Pologne',
    'La Grèce',
    'La Turquie',
    'Le Maroc',
    "L'Algérie",
    'La Tunisie',
    "L'Égypte",
    'Le Sénégal',
    'Le Canada',
    'Les États-Unis',
    'Le Mexique',
    'Le Brésil',
    "L'Argentine",
    'Le Chili',
    'Le Pérou',
    'La Colombie',
    'Le Japon',
    'La Chine',
    "L'Inde",
    'La Thaïlande',
    'Le Vietnam',
    'La Russie',
    "L'Arabie saoudite",
  ]),
  ...group('Dessin animé', [
    'Les Schtroumpfs',
    'Les Simpson',
    'Cendrillon',
    'Les Aristochats',
    'Aladdin',
    'Pocahontas',
    'Mulan',
    'Hercule',
    'Bambi',
    'Dumbo',
    'Raiponce',
    'Encanto',
    'Toy Story',
    'Là-haut',
    'Cars',
    'Les Minions',
    'Zootopie',
    'Vice-Versa',
    'Rebelle',
    'Inspecteur Gadget',
    'Bugs Bunny',
    'Titeuf',
    'Peppa Pig',
    'Pat Patrouille',
    'Miraculous',
    'Les Razmoket',
    'Casimir',
    "Dora l'exploratrice",
    'Totally Spies',
    'Pokémon',
    'Dragon Ball',
    'Princesse Sarah',
    'Capitaine Flam',
    'Les Moomins',
    'Wall-E',
    'Les Bisounours',
    "Merlin l'enchanteur",
    'Princesse Mononoké',
  ]),
  ...group('Série TV', [
    'Kaamelott',
    'Camping Paradis',
    'Friends',
    'Stranger Things',
    'Engrenages',
    'Caméra café',
    'Bref',
    'Navarro',
    'Julie Lescaut',
    'Derrick',
    'Columbo',
    'Docteur House',
    "Grey's Anatomy",
    'Urgences',
    'Les Experts',
    'Prison Break',
    'Breaking Bad',
    'The Office',
    'Lupin',
    'HPI',
    'Capitaine Marleau',
    'Dallas',
    'Arabesque',
    'MacGyver',
    'Charmed',
    'Sherlock',
    'Downton Abbey',
    'Fort Boyard',
    'Koh-Lanta',
    'Pékin Express',
    'Top Chef',
    'Secret Story',
    'Star Academy',
    'The Voice',
    'Intervilles',
    'Thalassa',
  ]),
  ...group('Personnage historique', [
    'Napoléon Bonaparte',
    "Jeanne d'Arc",
    'Louis Quatorze',
    'Le Roi-Soleil',
    'Charlemagne',
    'Vercingétorix',
    'Jules César',
    'Cléopâtre',
    'Toutankhamon',
    'Christophe Colomb',
    'Michel-Ange',
    'Molière',
    'Marie Curie',
    'Louis Pasteur',
    'Albert Einstein',
    'Isaac Newton',
    'Galilée',
    'Gustave Eiffel',
    'Jules Verne',
    'Simone Veil',
    'Nelson Mandela',
    'Abraham Lincoln',
    'Neil Armstrong',
    'Youri Gagarine',
    'Pablo Picasso',
    'Claude Monet',
    'Henri Quatre',
    'François Premier',
    'Richelieu',
    'Robespierre',
    'Lafayette',
    'Attila',
    'Gengis Khan',
    'Ramsès Deux',
    "Aliénor d'Aquitaine",
    'Saint Louis',
  ]),
  ...group('Ville', [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Bordeaux',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Lille',
    'Rennes',
    'Nice',
    'Toulon',
    'Grenoble',
    'Angers',
    'Reims',
    'Le Havre',
    'Saint-Étienne',
    'Perpignan',
    'Biarritz',
    'Saint-Malo',
    'Avignon',
    'Carcassonne',
    'Annecy',
    'Cannes',
    'Ajaccio',
    'Bastia',
    'Londres',
    'Rome',
    'Madrid',
    'Barcelone',
    'Lisbonne',
    'Berlin',
    'Bruxelles',
    'Amsterdam',
    'Venise',
    'Florence',
    'Vienne',
    'Prague',
    'New York',
    'Los Angeles',
    'San Francisco',
    'Montréal',
    'Québec',
    'Buenos Aires',
    'Pékin',
    'Sydney',
    'Le Caire',
    'Marrakech',
    'Istanbul',
    'Athènes',
  ]),
  ...group('Monument', [
    'Big Ben',
    'Le Sphinx',
    'Le Sacré-Cœur',
    'Le Panthéon',
    'Les Invalides',
    'Le Parthénon',
    "L'Acropole",
    'Stonehenge',
    'Le Kremlin',
  ]),
  ...group('Instrument', [
    'Un violon',
    'Un violoncelle',
    'Une contrebasse',
    'Une harpe',
    'Une clarinette',
    'Un saxophone',
    'Une trompette',
    'Un tuba',
    'Une batterie',
    'Un tambour',
    'Un xylophone',
    'Un accordéon',
    'Un harmonica',
    'Une cornemuse',
    'Un orgue',
    'Un synthétiseur',
    'Un ukulélé',
    'Un banjo',
    'Une mandoline',
    'Des maracas',
    'Un triangle',
    'Des castagnettes',
    'Un djembé',
  ]),
  ...group('Vêtement', [
    'Un pantalon',
    'Un tee-shirt',
    'Une doudoune',
    'Un imperméable',
    'Une écharpe',
    'Un bonnet',
    'Des moufles',
    'Une casquette',
    'Une cravate',
    'Des chaussettes',
    'Des collants',
    'Des baskets',
    'Des pantoufles',
    'Des tongs',
    'Un smoking',
    'Une salopette',
  ]),
  ...group('Véhicule', [
    'Une ambulance',
    'Un autobus',
    'Un tramway',
    'Un métro',
    'Un vélo',
    'Un tandem',
    'Un tricycle',
    'Une trottinette',
    'Une moto',
    'Un scooter',
    'Un tracteur',
    'Une bétonnière',
    'Un camping-car',
    'Une caravane',
    'Une montgolfière',
    'Un hélicoptère',
    'Une fusée',
    'Un sous-marin',
    'Un paquebot',
    'Un voilier',
    'Un pédalo',
    'Un canoë',
    'Une barque',
    'Un téléphérique',
    'Un télésiège',
    'Une calèche',
    'Un traîneau',
    'La deux-chevaux',
  ]),
  ...group('Super-héros', [
    'Superman',
    'Batman',
    'Spider-Man',
    'Wonder Woman',
    'Iron Man',
    'Captain America',
    'Thor',
    'Black Panther',
    'Wolverine',
    'Les Avengers',
    'Les X-Men',
    'Flash',
    'Green Lantern',
    'Ant-Man',
    'Doctor Strange',
    'Captain Marvel',
    'Catwoman',
    'Robin',
    'Le Joker',
    'Deadpool',
    'Daredevil',
    'Black Widow',
    'Hawkeye',
    'Supergirl',
    "L'homme araignée",
  ]),
  ...group('Livre', [
    'Madame Bovary',
    'Germinal',
    "L'Étranger",
    'La Peste',
    'Bel-Ami',
    'Candide',
    "L'Avare",
    'Hamlet',
    'Robinson Crusoé',
    'Le Horla',
    'Le Lion',
    'Croc-Blanc',
  ]),
  ...group('Corps humain', [
    'Les sourcils',
    'Les cils',
    'Les paupières',
    'Les pommettes',
    'Le menton',
    'Le coude',
    'Le genou',
    'La cheville',
    'Le talon',
    'Le mollet',
    'La cuisse',
    'Le nombril',
    'Le cœur',
    'Les poumons',
    "L'estomac",
    'Le foie',
    'Les reins',
    'Le cerveau',
    'Le squelette',
  ]),
  ...group('Jeu vidéo', [
    'Tetris',
    'Mario Kart',
    'Minecraft',
    'Fortnite',
    'Les Sims',
    'Street Fighter',
    'Tomb Raider',
    'Rayman',
    'Space Invaders',
    'Donkey Kong',
    'Animal Crossing',
    'Just Dance',
    'FIFA',
    "Assassin's Creed",
    'Final Fantasy',
    'Crash Bandicoot',
    'Angry Birds',
    'Candy Crush',
    'Lemmings',
  ]),
];
